# action.yml
name: 'JARVIS'
description: 'Auto fix to follow MISRA rule on the branch which triggers a workflow'
inputs:
  token:
    description: 'GITHUB_TOKEN'
    default: ${{ github.token }}

runs:
  using: 'composite'
  steps:
    - name: Start!
      run: echo "START!"
      shell: bash
    - name: Set permissions as executable
      run: chmod +x -R $GITHUB_ACTION_PATH
      shell: bash
    - name: Write shell script to set env var
      run: python3 $GITHUB_ACTION_PATH/jarvis/setenv_writters.py
      shell: bash
    - name: Run action
      permissions: write-all
      run: $GITHUB_ACTION_PATH/jarvis/action.sh
      shell: bash
      env:
        TOKEN: ${{ inputs.token }}
